- hosts: jenkins-slave
  become: true

  tasks:
    - name: Update ubuntu report and cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Install Java JDK 11
      apt: 
        name: openjdk-11-jre
        state: present 
    
    - name: Install Maven
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
        dest: /opt
        

    - name: Extracting maven packages
      unarchive:
        src: /opt/apache-maven-3.9.5-bin.tar.gz
        dest: /opt
        remote_src: yes
